# netlify.toml (at repo root)

[functions]
  # Be explicit so Netlify doesn’t use a UI override accidentally:
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Attach a cron to the public route of your function
[[scheduled]]
  cron = "*/10 * * * *"         # every 10 minutes
  path = "/.netlify/functions/send-notifications"
