# netlify.toml (repo root)

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Attach the schedule to the function by NAME
[functions."send-notifications"]
schedule = "*/10 * * * *"   # every 10 minutes (UTC)
